spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        show_sql: true
        default_schema: public
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    enabled: true
  application:
    name: canyonlands-spring-api

