--liquibase formatted sql

--changeset walthersmulders:1
INSERT INTO book_genre (book_genre_id, genre, sub_genre)
VALUES (gen_random_uuid(), 'Arts & Entertainment', 'Art & Architecture'),
       (gen_random_uuid(), 'Arts & Entertainment', 'Art History'),
       (gen_random_uuid(), 'Arts & Entertainment', 'Dance'),
       (gen_random_uuid(), 'Arts & Entertainment', 'Design'),
       (gen_random_uuid(), 'Arts & Entertainment', 'Fashion'),
       (gen_random_uuid(), 'Arts & Entertainment', 'Film'),
       (gen_random_uuid(), 'Arts & Entertainment', 'Games'),
       (gen_random_uuid(), 'Arts & Entertainment', 'Interior Design'),
       (gen_random_uuid(), 'Arts & Entertainment', 'Media Arts'),
       (gen_random_uuid(), 'Arts & Entertainment', 'Music'),
       (gen_random_uuid(), 'Arts & Entertainment', 'Performing Arts'),
       (gen_random_uuid(), 'Arts & Entertainment', 'Photography'),
       (gen_random_uuid(), 'Arts & Entertainment', 'Radio'),
       (gen_random_uuid(), 'Arts & Entertainment', 'TV'),
       (gen_random_uuid(), 'Arts & Entertainment', 'Theater'),
       (gen_random_uuid(), 'Arts & Entertainment', 'Visual Arts'),
       (gen_random_uuid(), 'Biographies & Memoirs', 'Arts & Entertainment'),
       (gen_random_uuid(), 'Biographies & Memoirs', 'Business'),
       (gen_random_uuid(), 'Biographies & Memoirs', 'Culinary'),
       (gen_random_uuid(), 'Biographies & Memoirs', 'Gay & Lesbian'),
       (gen_random_uuid(), 'Biographies & Memoirs', 'Historical'),
       (gen_random_uuid(), 'Biographies & Memoirs', 'Literary'),
       (gen_random_uuid(), 'Biographies & Memoirs', 'Media & Journalism'),
       (gen_random_uuid(), 'Biographies & Memoirs', 'Military'),
       (gen_random_uuid(), 'Biographies & Memoirs', 'Politics'),
       (gen_random_uuid(), 'Biographies & Memoirs', 'Religious'),
       (gen_random_uuid(), 'Biographies & Memoirs', 'Science & Technology'),
       (gen_random_uuid(), 'Biographies & Memoirs', 'Sports'),
       (gen_random_uuid(), 'Biographies & Memoirs', 'Women'),
       (gen_random_uuid(), 'Business & Personal Finance', 'Accounting'),
       (gen_random_uuid(), 'Business & Personal Finance', 'Careers'),
       (gen_random_uuid(), 'Business & Personal Finance', 'Economics'),
       (gen_random_uuid(), 'Business & Personal Finance', 'Finance'),
       (gen_random_uuid(), 'Business & Personal Finance', 'Hospitality'),
       (gen_random_uuid(), 'Business & Personal Finance', 'Industries & Professions'),
       (gen_random_uuid(), 'Business & Personal Finance', 'Marketing & Sales'),
       (gen_random_uuid(), 'Business & Personal Finance', 'Personal Finance'),
       (gen_random_uuid(), 'Business & Personal Finance', 'Real Estate'),
       (gen_random_uuid(), 'Business & Personal Finance', 'Reference'),
       (gen_random_uuid(), 'Business & Personal Finance', 'Small Business & Entrepreneurship'),
       (gen_random_uuid(), 'Children & Teens', 'Children''s Fiction'),
       (gen_random_uuid(), 'Children & Teens', 'Children''s Nonfiction'),
       (gen_random_uuid(), 'Comics & Graphic Novels', 'Comics'),
       (gen_random_uuid(), 'Comics & Graphic Novels', 'Graphic Novels'),
       (gen_random_uuid(), 'Comics & Graphic Novels', 'Manga'),
       (gen_random_uuid(), 'Communications & Media', 'Broadcasting'),
       (gen_random_uuid(), 'Communications & Media', 'Digital Media'),
       (gen_random_uuid(), 'Communications & Media', 'Journalism'),
       (gen_random_uuid(), 'Communications & Media', 'Photojournalism'),
       (gen_random_uuid(), 'Communications & Media', 'Print'),
       (gen_random_uuid(), 'Communications & Media', 'Speech'),
       (gen_random_uuid(), 'Communications & Media', 'Writing'),
       (gen_random_uuid(), 'Computers & Internet', 'Computers'),
       (gen_random_uuid(), 'Computers & Internet', 'Databases'),
       (gen_random_uuid(), 'Computers & Internet', 'Digital Media'),
       (gen_random_uuid(), 'Computers & Internet', 'Internet'),
       (gen_random_uuid(), 'Computers & Internet', 'Network'),
       (gen_random_uuid(), 'Computers & Internet', 'Operating System'),
       (gen_random_uuid(), 'Computers & Internet', 'Programming'),
       (gen_random_uuid(), 'Computers & Internet', 'Software'),
       (gen_random_uuid(), 'Computers & Internet', 'System Administration'),
       (gen_random_uuid(), 'Cookbooks, Food & Wine', 'Beverages'),
       (gen_random_uuid(), 'Cookbooks, Food & Wine', 'Courses & Dishes'),
       (gen_random_uuid(), 'Cookbooks, Food & Wine', 'Culinary Arts'),
       (gen_random_uuid(), 'Cookbooks, Food & Wine', 'Methods'),
       (gen_random_uuid(), 'Cookbooks, Food & Wine', 'Reference'),
       (gen_random_uuid(), 'Cookbooks, Food & Wine', 'Regional & Ethnic'),
       (gen_random_uuid(), 'Cookbooks, Food & Wine', 'Special Diet'),
       (gen_random_uuid(), 'Cookbooks, Food & Wine', 'Special Occasions'),
       (gen_random_uuid(), 'Cookbooks, Food & Wine', 'Specific Ingredients'),
       (gen_random_uuid(), 'Fiction & Literature', 'Action & Adventure'),
       (gen_random_uuid(), 'Fiction & Literature', 'African American'),
       (gen_random_uuid(), 'Fiction & Literature', 'Anthologies'),
       (gen_random_uuid(), 'Fiction & Literature', 'Classics'),
       (gen_random_uuid(), 'Fiction & Literature', 'Comparative Literature'),
       (gen_random_uuid(), 'Fiction & Literature', 'Drama'),
       (gen_random_uuid(), 'Fiction & Literature', 'Essays'),
       (gen_random_uuid(), 'Fiction & Literature', 'Fairy Tales, Myths & Fables'),
       (gen_random_uuid(), 'Fiction & Literature', 'Family'),
       (gen_random_uuid(), 'Fiction & Literature', 'Gay'),
       (gen_random_uuid(), 'Fiction & Literature', 'Ghost'),
       (gen_random_uuid(), 'Fiction & Literature', 'Historical'),
       (gen_random_uuid(), 'Fiction & Literature', 'Horror'),
       (gen_random_uuid(), 'Fiction & Literature', 'Light Novels'),
       (gen_random_uuid(), 'Fiction & Literature', 'Literary'),
       (gen_random_uuid(), 'Fiction & Literature', 'Literary Criticism'),
       (gen_random_uuid(), 'Fiction & Literature', 'Poetry'),
       (gen_random_uuid(), 'Fiction & Literature', 'Religious'),
       (gen_random_uuid(), 'Fiction & Literature', 'Short Stories'),
       (gen_random_uuid(), 'Health, Mind & Body', 'Diet & Nutrition'),
       (gen_random_uuid(), 'Health, Mind & Body', 'Health & Fitness'),
       (gen_random_uuid(), 'Health, Mind & Body', 'Psychology'),
       (gen_random_uuid(), 'Health, Mind & Body', 'Self-Improvement'),
       (gen_random_uuid(), 'Health, Mind & Body', 'Spirituality'),
       (gen_random_uuid(), 'History', 'Africa'),
       (gen_random_uuid(), 'History', 'Americas'),
       (gen_random_uuid(), 'History', 'Ancient'),
       (gen_random_uuid(), 'History', 'Asia'),
       (gen_random_uuid(), 'History', 'Australia & Oceania'),
       (gen_random_uuid(), 'History', 'Europe'),
       (gen_random_uuid(), 'History', 'Latin America'),
       (gen_random_uuid(), 'History', 'Middle East'),
       (gen_random_uuid(), 'History', 'Military'),
       (gen_random_uuid(), 'History', 'United States'),
       (gen_random_uuid(), 'History', 'World'),
       (gen_random_uuid(), 'Humor', 'Jokes & Riddles'),
       (gen_random_uuid(), 'Kids', 'Animals'),
       (gen_random_uuid(), 'Kids', 'Arts & Entertainment'),
       (gen_random_uuid(), 'Kids', 'Basic Concepts'),
       (gen_random_uuid(), 'Kids', 'Biography'),
       (gen_random_uuid(), 'Kids', 'Careers & Occupations'),
       (gen_random_uuid(), 'Kids', 'Computers & Technology'),
       (gen_random_uuid(), 'Kids', 'Cooking & Food'),
       (gen_random_uuid(), 'Kids', 'Family'),
       (gen_random_uuid(), 'Kids', 'Fiction'),
       (gen_random_uuid(), 'Kids', 'Games & Activities'),
       (gen_random_uuid(), 'Kids', 'General Nonfiction'),
       (gen_random_uuid(), 'Kids', 'Government'),
       (gen_random_uuid(), 'Kids', 'Health'),
       (gen_random_uuid(), 'Kids', 'History'),
       (gen_random_uuid(), 'Kids', 'Holidays & Celebrations'),
       (gen_random_uuid(), 'Kids', 'Humor'),
       (gen_random_uuid(), 'Kids', 'Learning to Read'),
       (gen_random_uuid(), 'Kids', 'Nursery Rhymes'),
       (gen_random_uuid(), 'Kids', 'Poetry'),
       (gen_random_uuid(), 'Kids', 'Reference'),
       (gen_random_uuid(), 'Kids', 'Religion'),
       (gen_random_uuid(), 'Kids', 'Science & Nature'),
       (gen_random_uuid(), 'Kids', 'Social Issues'),
       (gen_random_uuid(), 'Kids', 'Social Studies'),
       (gen_random_uuid(), 'Kids', 'Sports & Recreation'),
       (gen_random_uuid(), 'Kids', 'Transportation'),
       (gen_random_uuid(), 'Lifestyle & Home', 'Antiques & Collectibles'),
       (gen_random_uuid(), 'Lifestyle & Home', 'Crafts & Hobbies'),
       (gen_random_uuid(), 'Lifestyle & Home', 'Gardening'),
       (gen_random_uuid(), 'Lifestyle & Home', 'Pets'),
       (gen_random_uuid(), 'Military & Warfare', 'General'),
       (gen_random_uuid(), 'Mysteries & Thrillers', 'British Detectives'),
       (gen_random_uuid(), 'Mysteries & Thrillers', 'Cozy'),
       (gen_random_uuid(), 'Mysteries & Thrillers', 'Hard-Boiled'),
       (gen_random_uuid(), 'Mysteries & Thrillers', 'Historical'),
       (gen_random_uuid(), 'Mysteries & Thrillers', 'Police Procedural'),
       (gen_random_uuid(), 'Mysteries & Thrillers', 'Short Stories'),
       (gen_random_uuid(), 'Mysteries & Thrillers', 'Women Sleuths'),
       (gen_random_uuid(), 'Nonfiction', 'Family & Relationship'),
       (gen_random_uuid(), 'Nonfiction', 'Philosophy'),
       (gen_random_uuid(), 'Nonfiction', 'Social Science'),
       (gen_random_uuid(), 'Nonfiction', 'Transportation'),
       (gen_random_uuid(), 'Nonfiction', 'True Crime'),
       (gen_random_uuid(), 'Parenting', 'General'),
       (gen_random_uuid(), 'Politics & Current Events', 'Current Events'),
       (gen_random_uuid(), 'Politics & Current Events', 'Foreign Policy & International Relations'),
       (gen_random_uuid(), 'Politics & Current Events', 'Relations'),
       (gen_random_uuid(), 'Politics & Current Events', 'Local Government'),
       (gen_random_uuid(), 'Politics & Current Events', 'National Government'),
       (gen_random_uuid(), 'Politics & Current Events', 'Political Science'),
       (gen_random_uuid(), 'Politics & Current Events', 'Public Administration'),
       (gen_random_uuid(), 'Politics & Current Events', 'World Affairs'),
       (gen_random_uuid(), 'Professional & Technical', 'Design'),
       (gen_random_uuid(), 'Professional & Technical', 'Engineering'),
       (gen_random_uuid(), 'Professional & Technical', 'Law'),
       (gen_random_uuid(), 'Professional & Technical', 'Medical'),
       (gen_random_uuid(), 'Professional & Technical', 'Education'),
       (gen_random_uuid(), 'Reference', 'Almanacs & Yearbooks'),
       (gen_random_uuid(), 'Reference', 'Atlases & Maps'),
       (gen_random_uuid(), 'Reference', 'Catalogs & Directories'),
       (gen_random_uuid(), 'Reference', 'Consumer Guides'),
       (gen_random_uuid(), 'Reference', 'Dictionaries & Thesauruses'),
       (gen_random_uuid(), 'Reference', 'Encyclopedias'),
       (gen_random_uuid(), 'Reference', 'Etiquette'),
       (gen_random_uuid(), 'Reference', 'Foreign Languages'),
       (gen_random_uuid(), 'Reference', 'Manuals'),
       (gen_random_uuid(), 'Reference', 'Quotations'),
       (gen_random_uuid(), 'Reference', 'Study Aids'),
       (gen_random_uuid(), 'Reference', 'Words & Language'),
       (gen_random_uuid(), 'Reference', 'Writing'),
       (gen_random_uuid(), 'Religion & Spirituality', 'Bible Studies'),
       (gen_random_uuid(), 'Religion & Spirituality', 'Bibles'),
       (gen_random_uuid(), 'Religion & Spirituality', 'Buddhism'),
       (gen_random_uuid(), 'Religion & Spirituality', 'Christianity'),
       (gen_random_uuid(), 'Religion & Spirituality', 'Comparative Religion'),
       (gen_random_uuid(), 'Religion & Spirituality', 'Hinduism'),
       (gen_random_uuid(), 'Religion & Spirituality', 'Islam'),
       (gen_random_uuid(), 'Religion & Spirituality', 'Judaism'),
       (gen_random_uuid(), 'Romance', 'Contemporary'),
       (gen_random_uuid(), 'Romance', 'Gay & Lesbian'),
       (gen_random_uuid(), 'Romance', 'Historical'),
       (gen_random_uuid(), 'Romance', 'Holiday'),
       (gen_random_uuid(), 'Romance', 'Inspirational'),
       (gen_random_uuid(), 'Romance', 'Military'),
       (gen_random_uuid(), 'Romance', 'Multicultural'),
       (gen_random_uuid(), 'Romance', 'New Adult'),
       (gen_random_uuid(), 'Romance', 'Paranormal'),
       (gen_random_uuid(), 'Romance', 'Romantic Comedy'),
       (gen_random_uuid(), 'Romance', 'Short Stories'),
       (gen_random_uuid(), 'Romance', 'Suspense'),
       (gen_random_uuid(), 'Romance', 'Western'),
       (gen_random_uuid(), 'Romance', 'Wholesome'),
       (gen_random_uuid(), 'Sci-Fi & Fantasy', 'Fantasy'),
       (gen_random_uuid(), 'Sci-Fi & Fantasy', 'Science Fiction'),
       (gen_random_uuid(), 'Sci-Fi & Fantasy', 'Science Fiction & Literature'),
       (gen_random_uuid(), 'Science & Nature', 'Agriculture'),
       (gen_random_uuid(), 'Science & Nature', 'Astronomy'),
       (gen_random_uuid(), 'Science & Nature', 'Atmosphere'),
       (gen_random_uuid(), 'Science & Nature', 'Biology'),
       (gen_random_uuid(), 'Science & Nature', 'Chemistry'),
       (gen_random_uuid(), 'Science & Nature', 'Earth Sciences'),
       (gen_random_uuid(), 'Science & Nature', 'Ecology'),
       (gen_random_uuid(), 'Science & Nature', 'Environment'),
       (gen_random_uuid(), 'Science & Nature', 'Essays'),
       (gen_random_uuid(), 'Science & Nature', 'Geography'),
       (gen_random_uuid(), 'Science & Nature', 'Geology'),
       (gen_random_uuid(), 'Science & Nature', 'History'),
       (gen_random_uuid(), 'Science & Nature', 'Life Sciences'),
       (gen_random_uuid(), 'Science & Nature', 'Mathematics'),
       (gen_random_uuid(), 'Science & Nature', 'Nature'),
       (gen_random_uuid(), 'Science & Nature', 'Physics'),
       (gen_random_uuid(), 'Science & Nature', 'Reference'),
       (gen_random_uuid(), 'Sports & Outdoors', 'Baseball'),
       (gen_random_uuid(), 'Sports & Outdoors', 'Basketball'),
       (gen_random_uuid(), 'Sports & Outdoors', 'Boxing'),
       (gen_random_uuid(), 'Sports & Outdoors', 'Coaching'),
       (gen_random_uuid(), 'Sports & Outdoors', 'Cricket'),
       (gen_random_uuid(), 'Sports & Outdoors', 'Cycling'),
       (gen_random_uuid(), 'Sports & Outdoors', 'Equestrian'),
       (gen_random_uuid(), 'Sports & Outdoors', 'Extreme Sports'),
       (gen_random_uuid(), 'Sports & Outdoors', 'Football'),
       (gen_random_uuid(), 'Sports & Outdoors', 'Golf'),
       (gen_random_uuid(), 'Sports & Outdoors', 'Hockey'),
       (gen_random_uuid(), 'Sports & Outdoors', 'Martial Arts & Self Defence'),
       (gen_random_uuid(), 'Sports & Outdoors', 'Motor Sports'),
       (gen_random_uuid(), 'Sports & Outdoors', 'Mountaineering'),
       (gen_random_uuid(), 'Sports & Outdoors', 'Outdoors'),
       (gen_random_uuid(), 'Sports & Outdoors', 'Racket Sports'),
       (gen_random_uuid(), 'Sports & Outdoors', 'Reference'),
       (gen_random_uuid(), 'Sports & Outdoors', 'Rugby'),
       (gen_random_uuid(), 'Sports & Outdoors', 'Running'),
       (gen_random_uuid(), 'Sports & Outdoors', 'Soccer'),
       (gen_random_uuid(), 'Sports & Outdoors', 'Training'),
       (gen_random_uuid(), 'Sports & Outdoors', 'Water Sports'),
       (gen_random_uuid(), 'Sports & Outdoors', 'Winter Sports'),
       (gen_random_uuid(), 'Travel & Adventure', 'Africa'),
       (gen_random_uuid(), 'Travel & Adventure', 'Asia'),
       (gen_random_uuid(), 'Travel & Adventure', 'Canada'),
       (gen_random_uuid(), 'Travel & Adventure', 'Caribbean'),
       (gen_random_uuid(), 'Travel & Adventure', 'Essays & Memoirs'),
       (gen_random_uuid(), 'Travel & Adventure', 'Europe'),
       (gen_random_uuid(), 'Travel & Adventure', 'Latin America'),
       (gen_random_uuid(), 'Travel & Adventure', 'Middle East'),
       (gen_random_uuid(), 'Travel & Adventure', 'Specialty Travel'),
       (gen_random_uuid(), 'Travel & Adventure', 'United States'),
       (gen_random_uuid(), 'Young Adult', 'Animals'),
       (gen_random_uuid(), 'Young Adult', 'Arts & Entertainment'),
       (gen_random_uuid(), 'Young Adult', 'Biography'),
       (gen_random_uuid(), 'Young Adult', 'Careers & Occupations'),
       (gen_random_uuid(), 'Young Adult', 'Coming of Age'),
       (gen_random_uuid(), 'Young Adult', 'Computers & Technology'),
       (gen_random_uuid(), 'Young Adult', 'Cooking & Food'),
       (gen_random_uuid(), 'Young Adult', 'Family'),
       (gen_random_uuid(), 'Young Adult', 'Fiction'),
       (gen_random_uuid(), 'Young Adult', 'Games & Activities'),
       (gen_random_uuid(), 'Young Adult', 'General Nonfiction'),
       (gen_random_uuid(), 'Young Adult', 'Health'),
       (gen_random_uuid(), 'Young Adult', 'History'),
       (gen_random_uuid(), 'Young Adult', 'Holidays & Celebrations'),
       (gen_random_uuid(), 'Young Adult', 'Humor'),
       (gen_random_uuid(), 'Young Adult', 'Poetry'),
       (gen_random_uuid(), 'Young Adult', 'Politics & Government'),
       (gen_random_uuid(), 'Young Adult', 'Reference'),
       (gen_random_uuid(), 'Young Adult', 'Religion'),
       (gen_random_uuid(), 'Young Adult', 'Science & Nature'),
       (gen_random_uuid(), 'Young Adult', 'Social Studies'),
       (gen_random_uuid(), 'Young Adult', 'Sports & Recreation'),
       (gen_random_uuid(), 'Young Adult', 'Transportation');
